# Generated by Django 4.0.5 on 2022-06-20 14:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duelNumber', models.IntegerField(default='')),
                ('stage', models.IntegerField(default='')),
                ('open', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('started_date', models.DateTimeField()),
                ('number_of_players', models.IntegerField(choices=[(4, 4), (8, 8), (16, 16), (32, 32), (64, 64)])),
                ('owner', models.IntegerField(default=1)),
                ('closed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_one_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('player_two_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('duel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TournamentApp.matchpair')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TournamentApp.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='matchpair',
            name='player_one',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_one', to='TournamentApp.player'),
        ),
        migrations.AddField(
            model_name='matchpair',
            name='player_two',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_two', to='TournamentApp.player'),
        ),
        migrations.AddField(
            model_name='matchpair',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament', to='TournamentApp.tournament'),
        ),
    ]
