# Generated by Django 4.0.5 on 2022-06-20 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentApp', '0002_delete_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winner',
            name='player_one_score',
        ),
        migrations.RemoveField(
            model_name='winner',
            name='player_two_score',
        ),
        migrations.AddField(
            model_name='winner',
            name='champion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='TournamentApp.player'),
        ),
    ]
