# Generated by Django 4.0.5 on 2022-06-20 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentApp', '0003_remove_winner_player_one_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winner',
            name='champion',
        ),
        migrations.AddField(
            model_name='winner',
            name='player_one_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='winner',
            name='player_two_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
